// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeType int32

const (
	EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED  EnvelopeType = 0
	EnvelopeType_ENVELOPE_TYPE_KEY_EXCHANGE EnvelopeType = 1
	EnvelopeType_ENVELOPE_TYPE_SESSION_INIT EnvelopeType = 2
	EnvelopeType_ENVELOPE_TYPE_TASK         EnvelopeType = 3
	EnvelopeType_ENVELOPE_TYPE_TASK_RESULT  EnvelopeType = 4
	EnvelopeType_ENVELOPE_TYPE_HEARTBEAT    EnvelopeType = 5
	EnvelopeType_ENVELOPE_TYPE_ACK          EnvelopeType = 6
	EnvelopeType_ENVELOPE_TYPE_ERROR        EnvelopeType = 7
	EnvelopeType_ENVELOPE_TYPE_DISCONNECT   EnvelopeType = 8
	EnvelopeType_ENVELOPE_TYPE_RECONNECT    EnvelopeType = 9
	EnvelopeType_ENVELOPE_TYPE_TUNNEL_OPEN  EnvelopeType = 10
	EnvelopeType_ENVELOPE_TYPE_TUNNEL_DATA  EnvelopeType = 11
	EnvelopeType_ENVELOPE_TYPE_TUNNEL_CLOSE EnvelopeType = 12
)

// Enum value maps for EnvelopeType.
var (
	EnvelopeType_name = map[int32]string{
		0:  "ENVELOPE_TYPE_UNSPECIFIED",
		1:  "ENVELOPE_TYPE_KEY_EXCHANGE",
		2:  "ENVELOPE_TYPE_SESSION_INIT",
		3:  "ENVELOPE_TYPE_TASK",
		4:  "ENVELOPE_TYPE_TASK_RESULT",
		5:  "ENVELOPE_TYPE_HEARTBEAT",
		6:  "ENVELOPE_TYPE_ACK",
		7:  "ENVELOPE_TYPE_ERROR",
		8:  "ENVELOPE_TYPE_DISCONNECT",
		9:  "ENVELOPE_TYPE_RECONNECT",
		10: "ENVELOPE_TYPE_TUNNEL_OPEN",
		11: "ENVELOPE_TYPE_TUNNEL_DATA",
		12: "ENVELOPE_TYPE_TUNNEL_CLOSE",
	}
	EnvelopeType_value = map[string]int32{
		"ENVELOPE_TYPE_UNSPECIFIED":  0,
		"ENVELOPE_TYPE_KEY_EXCHANGE": 1,
		"ENVELOPE_TYPE_SESSION_INIT": 2,
		"ENVELOPE_TYPE_TASK":         3,
		"ENVELOPE_TYPE_TASK_RESULT":  4,
		"ENVELOPE_TYPE_HEARTBEAT":    5,
		"ENVELOPE_TYPE_ACK":          6,
		"ENVELOPE_TYPE_ERROR":        7,
		"ENVELOPE_TYPE_DISCONNECT":   8,
		"ENVELOPE_TYPE_RECONNECT":    9,
		"ENVELOPE_TYPE_TUNNEL_OPEN":  10,
		"ENVELOPE_TYPE_TUNNEL_DATA":  11,
		"ENVELOPE_TYPE_TUNNEL_CLOSE": 12,
	}
)

func (x EnvelopeType) Enum() *EnvelopeType {
	p := new(EnvelopeType)
	*p = x
	return p
}

func (x EnvelopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (EnvelopeType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x EnvelopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeType.Descriptor instead.
func (EnvelopeType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Envelope is the top-level message wrapper for all C2 communication.
// Every message is encrypted (XChaCha20-Poly1305), then serialized as Envelope.
type Envelope struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                        // Message ID (monotonic per session)
	Type         EnvelopeType           `protobuf:"varint,2,opt,name=type,proto3,enum=proto.EnvelopeType" json:"type,omitempty"`            // Message type discriminator
	Timestamp    uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix nano timestamp
	SessionToken []byte                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Session identifier (HMAC-based)
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_KeyExchange
	//	*Envelope_SessionInit
	//	*Envelope_Task
	//	*Envelope_TaskResult
	//	*Envelope_Heartbeat
	//	*Envelope_Ack
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	Nonce         []byte             `protobuf:"bytes,20,opt,name=nonce,proto3" json:"nonce,omitempty"`           // 24-byte XChaCha20 nonce
	Ciphertext    []byte             `protobuf:"bytes,21,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // Encrypted inner payload (binary EnvelopeInner)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Envelope) GetType() EnvelopeType {
	if x != nil {
		return x.Type
	}
	return EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetKeyExchange() *KeyExchange {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_KeyExchange); ok {
			return x.KeyExchange
		}
	}
	return nil
}

func (x *Envelope) GetSessionInit() *SessionInit {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SessionInit); ok {
			return x.SessionInit
		}
	}
	return nil
}

func (x *Envelope) GetTask() *Task {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Envelope) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Acknowledge {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_KeyExchange struct {
	KeyExchange *KeyExchange `protobuf:"bytes,10,opt,name=key_exchange,json=keyExchange,proto3,oneof"`
}

type Envelope_SessionInit struct {
	SessionInit *SessionInit `protobuf:"bytes,11,opt,name=session_init,json=sessionInit,proto3,oneof"`
}

type Envelope_Task struct {
	Task *Task `protobuf:"bytes,12,opt,name=task,proto3,oneof"`
}

type Envelope_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,13,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Acknowledge `protobuf:"bytes,15,opt,name=ack,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

func (*Envelope_KeyExchange) isEnvelope_Payload() {}

func (*Envelope_SessionInit) isEnvelope_Payload() {}

func (*Envelope_Task) isEnvelope_Payload() {}

func (*Envelope_TaskResult) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

// EnvelopeInner is the cleartext payload before encryption.
type EnvelopeInner struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         EnvelopeType           `protobuf:"varint,2,opt,name=type,proto3,enum=proto.EnvelopeType" json:"type,omitempty"`
	Timestamp    uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionToken []byte                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EnvelopeInner_KeyExchange
	//	*EnvelopeInner_SessionInit
	//	*EnvelopeInner_Task
	//	*EnvelopeInner_TaskResult
	//	*EnvelopeInner_Heartbeat
	//	*EnvelopeInner_Ack
	//	*EnvelopeInner_Error
	Payload       isEnvelopeInner_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeInner) Reset() {
	*x = EnvelopeInner{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeInner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeInner) ProtoMessage() {}

func (x *EnvelopeInner) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeInner.ProtoReflect.Descriptor instead.
func (*EnvelopeInner) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *EnvelopeInner) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnvelopeInner) GetType() EnvelopeType {
	if x != nil {
		return x.Type
	}
	return EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED
}

func (x *EnvelopeInner) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EnvelopeInner) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

func (x *EnvelopeInner) GetPayload() isEnvelopeInner_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnvelopeInner) GetKeyExchange() *KeyExchange {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_KeyExchange); ok {
			return x.KeyExchange
		}
	}
	return nil
}

func (x *EnvelopeInner) GetSessionInit() *SessionInit {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_SessionInit); ok {
			return x.SessionInit
		}
	}
	return nil
}

func (x *EnvelopeInner) GetTask() *Task {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *EnvelopeInner) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *EnvelopeInner) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *EnvelopeInner) GetAck() *Acknowledge {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *EnvelopeInner) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*EnvelopeInner_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelopeInner_Payload interface {
	isEnvelopeInner_Payload()
}

type EnvelopeInner_KeyExchange struct {
	KeyExchange *KeyExchange `protobuf:"bytes,10,opt,name=key_exchange,json=keyExchange,proto3,oneof"`
}

type EnvelopeInner_SessionInit struct {
	SessionInit *SessionInit `protobuf:"bytes,11,opt,name=session_init,json=sessionInit,proto3,oneof"`
}

type EnvelopeInner_Task struct {
	Task *Task `protobuf:"bytes,12,opt,name=task,proto3,oneof"`
}

type EnvelopeInner_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,13,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type EnvelopeInner_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,14,opt,name=heartbeat,proto3,oneof"`
}

type EnvelopeInner_Ack struct {
	Ack *Acknowledge `protobuf:"bytes,15,opt,name=ack,proto3,oneof"`
}

type EnvelopeInner_Error struct {
	Error *Error `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

func (*EnvelopeInner_KeyExchange) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_SessionInit) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_Task) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_TaskResult) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_Heartbeat) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_Ack) isEnvelopeInner_Payload() {}

func (*EnvelopeInner_Error) isEnvelopeInner_Payload() {}

// KeyExchange: X25519 public key + transport negotiation.
type KeyExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32-byte X25519 public key
	Transports    []string               `protobuf:"bytes,2,rep,name=transports,proto3" json:"transports,omitempty"`                // Supported transports (e.g., ["tcp+tls", "wss"])
	AgentVersion  string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Padding       []byte                 `protobuf:"bytes,4,opt,name=padding,proto3" json:"padding,omitempty"` // Random padding (anti-fingerprinting)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyExchange) Reset() {
	*x = KeyExchange{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchange) ProtoMessage() {}

func (x *KeyExchange) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchange.ProtoReflect.Descriptor instead.
func (*KeyExchange) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *KeyExchange) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *KeyExchange) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *KeyExchange) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *KeyExchange) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

// SessionInit: Agent metadata sent after key exchange.
type SessionInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Pid           uint32                 `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	LocalIp       string                 `protobuf:"bytes,7,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	PublicIp      string                 `protobuf:"bytes,8,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	MacAddress    string                 `protobuf:"bytes,9,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	AgentId       string                 `protobuf:"bytes,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,11,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInit) Reset() {
	*x = SessionInit{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInit) ProtoMessage() {}

func (x *SessionInit) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInit.ProtoReflect.Descriptor instead.
func (*SessionInit) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SessionInit) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SessionInit) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SessionInit) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SessionInit) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SessionInit) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInit) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *SessionInit) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *SessionInit) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *SessionInit) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *SessionInit) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionInit) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// Task: Command from server to agent.
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`              // Unique task identifier (UUID)
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                          // Command string
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                          // Optional binary payload
	TimeoutSec    uint32                 `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"` // Timeout in seconds
	Async         bool                   `protobuf:"varint,5,opt,name=async,proto3" json:"async,omitempty"`                             // If true, agent sends result later
	Module        string                 `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`                            // Module to load/execute
	Channel       uint32                 `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`                         // Multiplexed channel ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *Task) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *Task) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Task) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// TaskResult: Agent response to a task.
type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // Text output
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`     // Binary output (files, screenshots, etc.)
	ExitCode      uint32                 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskResult) GetExitCode() uint32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Heartbeat: Periodic keep-alive message.
type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionTimeSec uint32                 `protobuf:"varint,2,opt,name=session_time_sec,json=sessionTimeSec,proto3" json:"session_time_sec,omitempty"` // How long agent has been running
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetSessionTimeSec() uint32 {
	if x != nil {
		return x.SessionTimeSec
	}
	return 0
}

// Acknowledge: Generic ACK.
type Acknowledge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckId         uint32                 `protobuf:"varint,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"` // Message ID being acknowledged
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledge) Reset() {
	*x = Acknowledge{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledge) ProtoMessage() {}

func (x *Acknowledge) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledge.ProtoReflect.Descriptor instead.
func (*Acknowledge) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Acknowledge) GetAckId() uint32 {
	if x != nil {
		return x.AckId
	}
	return 0
}

func (x *Acknowledge) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Error: Error notification.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []byte                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

// TunnelOpen: Open a tunnel connection through the agent.
type TunnelOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // target host:port
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpen) Reset() {
	*x = TunnelOpen{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpen) ProtoMessage() {}

func (x *TunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpen.ProtoReflect.Descriptor instead.
func (*TunnelOpen) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *TunnelOpen) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelOpen) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TunnelOpen) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// TunnelData: Bidirectional data relay through a tunnel.
type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Close         bool                   `protobuf:"varint,3,opt,name=close,proto3" json:"close,omitempty"` // Close signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *TunnelData) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelData) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x05proto\"\x92\x04\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.proto.EnvelopeTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12#\n" +
	"\rsession_token\x18\x04 \x01(\fR\fsessionToken\x127\n" +
	"\fkey_exchange\x18\n" +
	" \x01(\v2\x12.proto.KeyExchangeH\x00R\vkeyExchange\x127\n" +
	"\fsession_init\x18\v \x01(\v2\x12.proto.SessionInitH\x00R\vsessionInit\x12!\n" +
	"\x04task\x18\f \x01(\v2\v.proto.TaskH\x00R\x04task\x124\n" +
	"\vtask_result\x18\r \x01(\v2\x11.proto.TaskResultH\x00R\n" +
	"taskResult\x120\n" +
	"\theartbeat\x18\x0e \x01(\v2\x10.proto.HeartbeatH\x00R\theartbeat\x12&\n" +
	"\x03ack\x18\x0f \x01(\v2\x12.proto.AcknowledgeH\x00R\x03ack\x12$\n" +
	"\x05error\x18\x10 \x01(\v2\f.proto.ErrorH\x00R\x05error\x12\x14\n" +
	"\x05nonce\x18\x14 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x15 \x01(\fR\n" +
	"ciphertextB\t\n" +
	"\apayload\"\xe1\x03\n" +
	"\rEnvelopeInner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.proto.EnvelopeTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12#\n" +
	"\rsession_token\x18\x04 \x01(\fR\fsessionToken\x127\n" +
	"\fkey_exchange\x18\n" +
	" \x01(\v2\x12.proto.KeyExchangeH\x00R\vkeyExchange\x127\n" +
	"\fsession_init\x18\v \x01(\v2\x12.proto.SessionInitH\x00R\vsessionInit\x12!\n" +
	"\x04task\x18\f \x01(\v2\v.proto.TaskH\x00R\x04task\x124\n" +
	"\vtask_result\x18\r \x01(\v2\x11.proto.TaskResultH\x00R\n" +
	"taskResult\x120\n" +
	"\theartbeat\x18\x0e \x01(\v2\x10.proto.HeartbeatH\x00R\theartbeat\x12&\n" +
	"\x03ack\x18\x0f \x01(\v2\x12.proto.AcknowledgeH\x00R\x03ack\x12$\n" +
	"\x05error\x18\x10 \x01(\v2\f.proto.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x8b\x01\n" +
	"\vKeyExchange\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1e\n" +
	"\n" +
	"transports\x18\x02 \x03(\tR\n" +
	"transports\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x18\n" +
	"\apadding\x18\x04 \x01(\fR\apadding\"\xaf\x02\n" +
	"\vSessionInit\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\rR\x03pid\x12\x19\n" +
	"\bis_admin\x18\x06 \x01(\bR\aisAdmin\x12\x19\n" +
	"\blocal_ip\x18\a \x01(\tR\alocalIp\x12\x1b\n" +
	"\tpublic_ip\x18\b \x01(\tR\bpublicIp\x12\x1f\n" +
	"\vmac_address\x18\t \x01(\tR\n" +
	"macAddress\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\v \x01(\tR\fagentVersion\"\xbc\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\rR\n" +
	"timeoutSec\x12\x14\n" +
	"\x05async\x18\x05 \x01(\bR\x05async\x12\x16\n" +
	"\x06module\x18\x06 \x01(\tR\x06module\x12\x18\n" +
	"\achannel\x18\a \x01(\rR\achannel\"\xad\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\rR\bexitCode\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"S\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12(\n" +
	"\x10session_time_sec\x18\x02 \x01(\rR\x0esessionTimeSec\">\n" +
	"\vAcknowledge\x12\x15\n" +
	"\x06ack_id\x18\x01 \x01(\rR\x05ackId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\fR\adetails\"[\n" +
	"\n" +
	"TunnelOpen\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\"S\n" +
	"\n" +
	"TunnelData\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x03 \x01(\bR\x05close*\x8a\x03\n" +
	"\fEnvelopeType\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aENVELOPE_TYPE_KEY_EXCHANGE\x10\x01\x12\x1e\n" +
	"\x1aENVELOPE_TYPE_SESSION_INIT\x10\x02\x12\x16\n" +
	"\x12ENVELOPE_TYPE_TASK\x10\x03\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_TASK_RESULT\x10\x04\x12\x1b\n" +
	"\x17ENVELOPE_TYPE_HEARTBEAT\x10\x05\x12\x15\n" +
	"\x11ENVELOPE_TYPE_ACK\x10\x06\x12\x17\n" +
	"\x13ENVELOPE_TYPE_ERROR\x10\a\x12\x1c\n" +
	"\x18ENVELOPE_TYPE_DISCONNECT\x10\b\x12\x1b\n" +
	"\x17ENVELOPE_TYPE_RECONNECT\x10\t\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_TUNNEL_OPEN\x10\n" +
	"\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_TUNNEL_DATA\x10\v\x12\x1e\n" +
	"\x1aENVELOPE_TYPE_TUNNEL_CLOSE\x10\fB:Z8github.com/Ruby570bocadito/WorldC2/src/go/internal/protob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_messages_proto_goTypes = []any{
	(EnvelopeType)(0),     // 0: proto.EnvelopeType
	(*Envelope)(nil),      // 1: proto.Envelope
	(*EnvelopeInner)(nil), // 2: proto.EnvelopeInner
	(*KeyExchange)(nil),   // 3: proto.KeyExchange
	(*SessionInit)(nil),   // 4: proto.SessionInit
	(*Task)(nil),          // 5: proto.Task
	(*TaskResult)(nil),    // 6: proto.TaskResult
	(*Heartbeat)(nil),     // 7: proto.Heartbeat
	(*Acknowledge)(nil),   // 8: proto.Acknowledge
	(*Error)(nil),         // 9: proto.Error
	(*TunnelOpen)(nil),    // 10: proto.TunnelOpen
	(*TunnelData)(nil),    // 11: proto.TunnelData
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: proto.Envelope.type:type_name -> proto.EnvelopeType
	3,  // 1: proto.Envelope.key_exchange:type_name -> proto.KeyExchange
	4,  // 2: proto.Envelope.session_init:type_name -> proto.SessionInit
	5,  // 3: proto.Envelope.task:type_name -> proto.Task
	6,  // 4: proto.Envelope.task_result:type_name -> proto.TaskResult
	7,  // 5: proto.Envelope.heartbeat:type_name -> proto.Heartbeat
	8,  // 6: proto.Envelope.ack:type_name -> proto.Acknowledge
	9,  // 7: proto.Envelope.error:type_name -> proto.Error
	0,  // 8: proto.EnvelopeInner.type:type_name -> proto.EnvelopeType
	3,  // 9: proto.EnvelopeInner.key_exchange:type_name -> proto.KeyExchange
	4,  // 10: proto.EnvelopeInner.session_init:type_name -> proto.SessionInit
	5,  // 11: proto.EnvelopeInner.task:type_name -> proto.Task
	6,  // 12: proto.EnvelopeInner.task_result:type_name -> proto.TaskResult
	7,  // 13: proto.EnvelopeInner.heartbeat:type_name -> proto.Heartbeat
	8,  // 14: proto.EnvelopeInner.ack:type_name -> proto.Acknowledge
	9,  // 15: proto.EnvelopeInner.error:type_name -> proto.Error
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_KeyExchange)(nil),
		(*Envelope_SessionInit)(nil),
		(*Envelope_Task)(nil),
		(*Envelope_TaskResult)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Error)(nil),
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*EnvelopeInner_KeyExchange)(nil),
		(*EnvelopeInner_SessionInit)(nil),
		(*EnvelopeInner_Task)(nil),
		(*EnvelopeInner_TaskResult)(nil),
		(*EnvelopeInner_Heartbeat)(nil),
		(*EnvelopeInner_Ack)(nil),
		(*EnvelopeInner_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
